
# BSD Zero Clause License

# Copyright (c) 2025 David M Crumpton david.m.crumpton [at] gmail [dot] com

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
# 
# This is a GitLab CI/CD configuration file for a project that compiles C code,
# runs unit tests, performs linting, and deploys the application.
workflow:
  rules:
    - changes:
        - '*.c'
        - 'unittest/*'
        - 'Makefile'
        - '*.1'
        - '.gitlab-ci.yml'
        - '*.h'
        - '*.y'
      when: always
    - when: never


stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - openbsd
  script:
    - echo "Compiling the code..."
    - make clean
    - make
    - echo "âœ… Build  complete. Now go touch grass. ðŸŒ±"

  artifacts:
      paths:
        - "buffy"

unit-test-job:   # This job runs in the test stage.
  tags:
    - openbsd
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - rm -f -- ${HOME}/.buffy_save.btfd
    - make clean
    - make buffy-unittest
    - ./buffy-unittest | tee buffy-unittest.txt
  artifacts:
      paths:
        - "buffy-unittest.txt"
        - "buffy-unittest"

lint-test-job:   # This job also runs in the test stage.
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  tags:
    - openbsd
  script:
    - echo "Linting code w/cppcheck..."
    - make clean
    - cppcheck . | tee cppcheck.txt
    - echo "No lint issues found."
    - echo validating man page...
    - mandoc -Tlint -Werror -Wall -Wstyle buffy.6 | tee manodc_lint.txt
  artifacts:
      paths:
        - "cppcheck.txt"
        - "manodc_lint.txt"


deploy-job:      # This job runs in the deploy stage.
  tags:
    - openbsd
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/'
      when: always
    - when: never
